trainer:
  max_epochs: 100
  check_val_every_n_epoch: 1
  logger:
    class_path: lightning.pytorch.loggers.CSVLogger
    init_args:
      save_dir: runs
      name: stenosis_cropped_eomt_small_224_dinov2_skelrecall
model:
  class_path: training.mask_classification_instance.MaskClassificationInstance
  init_args:
    attn_mask_annealing_enabled: True
    attn_mask_annealing_start_steps: [8120, 20300, 32480]
    attn_mask_annealing_end_steps: [20300, 32480, 40600]
    warmup_steps: [406, 812]
    skeleton_coefficient: 1.0
    network:
      class_path: models.eomt.EoMT
      init_args:
        num_q: 100
        num_blocks: 3
        encoder:
          class_path: models.vit.ViT
          init_args:
            backbone_name: vit_small_patch14_dinov2.lvd142m
            patch_size: 14
data:
  class_path: datasets.coronary_instance.CoronaryInstance
  init_args:
    path: /home/dsa/new_seg_final/stenosis_cropped
    num_classes: 1
    img_size:
      - 224
      - 224
    skeleton_enabled: true
    skeleton_num_dilations: 2
    extra_augmentations_enabled: true
