trainer:
  max_epochs: 100
  check_val_every_n_epoch: 1
  logger:
    class_path: lightning.pytorch.loggers.CSVLogger
    init_args:
      save_dir: runs
      name: coronary_instance_eomt_small_512_dinov2
model:
  class_path: training.mask_classification_instance.MaskClassificationInstance
  init_args:
    attn_mask_annealing_enabled: True
    attn_mask_annealing_start_steps: [2960, 7400, 11840]
    attn_mask_annealing_end_steps: [7400, 11840, 14800]
    warmup_steps: [296, 592]
    network:
      class_path: models.eomt.EoMT
      init_args:
        num_q: 100
        num_blocks: 3
        encoder:
          class_path: models.vit.ViT
          init_args:
            backbone_name: vit_small_patch14_dinov2.lvd142m
            patch_size: 14
data:
  class_path: datasets.coronary_instance.CoronaryInstance
  init_args:
    extra_augmentations_enabled: true
